# Uncomment the next line to define a global platform for your project
platform :ios, '10.0'

target 'ViperServicesDemo' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for ViperServicesDemo
  pod "ViperServices", :path => "../ViperServices.podspec"

  target 'ViperServicesDemoTests' do
    inherit! :search_paths
    # Pods for testing
    pod "ViperServices", :path => "../ViperServices.podspec"
  end

end
