# Uncomment the next line to define a global platform for your project


target 'ViperServicesDemoIOS' do
  platform :ios, '10.0'
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for ViperServicesDemo
  pod "ViperServices", :path => "../ViperServices.podspec"

  target 'ViperServicesDemoTests' do
    inherit! :search_paths
    # Pods for testing
    pod "ViperServices", :path => "../ViperServices.podspec"
  end
  
end

target 'ViperServicesDemoMacOS' do
  platform :osx, '10.12'
  use_frameworks!
  pod "ViperServices", :path => "../ViperServices.podspec"
end
